---
services: docker

env:
  - distro: centos7
  - distro: ubuntu1604
  - distro: ubuntu1404
  # See: https://github.com/geerlingguy/ansible-role-glusterfs/issues/20
  # - distro: debian9
  # - distro: debian8

script:
  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # Make sure Gluster is running.
  # - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm sudo pgrep glusterd'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
